### ISSUE TITLE
godot 4

### ISSUE THREAD

**Issue by ghost** [Malod219/rex-is-godot#1]
Hi

Does this work in latest godot 4?
I'm a beginner and don't know how to use it even after reading the small instructions.
Is it possible to test in godot 4 and write a more detaillee installation tutorial?

**Comment by RisingThumb** [comment]
No plans to port to Godot 4. See email response I sent you. For more documentation refer to Rexpaint docs https://www.gridsagegames.com/blogs/blog2/MANUAL.txt since this just decompresses the .xp format in the same structure

**Comment by ghost** [comment]
FUCK YOU MOTHERFUCKER
